#!/bin/sh

# Launch SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

count_monitors()
{
	xrandr | grep -E '[^dis]connected' | grep "^$1" | wc -l
}  

# Assign workspaces to specific monitors
HDMI_MONITOR=$(count_monitors HDMI)
DP_MONITOR=$(count_monitors DP)

if [ $HDMI_MONITOR -eq 1 ] && [ $DP_MONITOR -eq 1 ]; then
	xrandr --output eDP --off --output HDMI-A-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --rate 69.93 --output DP-1-0 --mode 1920x1080 --pos 2560x0 --rotate normal --output DP-1-1 --off
	bspc monitor HDMI-A-0 -d 1 2 3 4 5
	bspc monitor DP-1-0 -d 6 
	bspc monitor eDP -r
elif [ $HDMI_MONITOR -eq 1 ] && [ $DP_MONITOR -eq 0 ]; then		 
 	xrandr --output eDP --off --output HDMI-A-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal --rate 69.93 --output DP-1-0 --off --output DP-1-1 --off
	bspc monitor HDMI-A-0 -d 1 2 3 4 5 6
	bspc monitor eDP -r
else
	xradnr --output eDP --mode 1920x1080 --rate 144 --primary --output DP-1-0 --off --output DP-1-1 --off	
	bspc monitor eDP -d 1 2 3 4 5 6
fi 

# Set general BSPWM appearance and behavior
bspc config border_width         1
bspc config focused_border_color "#690c6f"
bspc config window_gap           2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config bottom_padding 0
bspc config automatic_scheme monocle
bspc config initial_polarity second_child

# Arrange monitors with xrandr
~/.screenlayout/display.sh

# Autostart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
